[package]
name = "tls-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = {version="0.20"}
rustls-pemfile = {version="1"}
webpki-roots = {version="*"} # Internet Root certificates
