[package]
name = "tls-server-tokio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-rustls = "0.23"
tokio = {version="1", features=["rt", "macros", "net", "io-util"]}
rustls-pemfile = "1"